[package]
name = "iron_compress"
version = "0.1.0"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
keywords = ["iron", "hyper", "http"]

[dependencies]
flate2 = "0.2"
iron = "0.3"
modifier = "0.1"
